### ISSUE TITLE
Q10 and Q11 are contradicting.

### ISSUE THREAD

**Issue by marudhupandiyang** [lydiahallie/javascript-questions#105]
Question 10 says that ` functions are objects` and so we can set `bark.animal` to a value which is totally fine.

On the same lines Q11, where `Person` is a function and assigning `Person.getFullName` should also be completely fine. The issue would be only when `member.getFullName()` is executed, would not find an function with the name.

**Comment by lydiahallie** [comment]
They don't contradict.

We have a constructor function `Person`. To explain it the best way, it is possible to do:

`Person.animal = "dog"` 

When we then log `Person.animal`, `"dog"` will get returned. However, it is not added to the _prototype_. In question 11, I log the `member.getFullName()`, which is an instance of the `Person` constructor. `getFullName()` is not a function on the  `member` instance, since it's not been added to the prototype. You can only do this, by adding `Person.prototype.getFullname .... `
