### ISSUE TITLE
Question 35 answer incorrect

### ISSUE THREAD

**Issue by lauripiisang** [lydiahallie/javascript-questions#116]
question states that `new Boolean(false)` is not falsy.

This is not the case, at least in Node.js 8 and 10

Proof: 
![image](https://user-images.githubusercontent.com/5603529/60093186-7ace5b00-9751-11e9-8d4f-11a8c7c9707e.png)

https://repl.it/repls/GargantuanDeterminedFunnel

**Comment by lydiahallie** [comment]
This is because you're using `==` instead of the strict equal `===`. Since `new Boolean()` is an object wrapper, it's a truthy value. However, `new Boolean(false) === false` is falsy. 

Here you can read more about equal vs. strict equal https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

**Comment by papb** [comment]
Moreover, you can check that `!!(new Boolean(false))` yields `true`, so it is indeed truthy.

**Comment by lauripiisang** [comment]
The strict equality part you commented about doesn't make sense as `(0 === false)` returns `false`, but thanks for the falsy explanation, I alway assumed it to be explictly for context of non-strict boolean comparison.
