### ISSUE TITLE
javascript-questions#97 explaination a little wrong

### ISSUE THREAD

**Issue by SunGuoQiang123** [lydiahallie/javascript-questions#227]
Symbol key in object can be enumerable 
![image](https://user-images.githubusercontent.com/17311301/63569108-89e35500-c5aa-11e9-8e32-0d3ff34c60c2.png)
I think the reason is `Object.keys` just return the string key of the parameter object

**Comment by lydiahallie** [comment]
I did some research and turns out that they are indeed enumerable. However, they won't show up in:

-  `for-in` loops. "The for...in statement iterates over all non-Symbol, enumerable properties of an object." - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)
- `Object.keys` - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#Detection_Table)
- `Object.getOwnPropertyNames` - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#Detection_Table)

I should change the explanation, thanks!
