### ISSUE TITLE
Question 51

### ISSUE THREAD

**Issue by NexusDeveloper** [lydiahallie/javascript-questions#345]
Answer:
«Arguments are passed by *value*, **unless** their value is an object, then they're passed by *reference*».
A little lower:
«The value of person is an object. The argument member has a (copied) reference to the *same* object.»

Question:
Why was the person passed by reference if it is an object?
I think there is an mistake in the first sentence and should be like this:
«Arguments are passed by *value*, **if** their value is an object, then they're passed by *reference*»
or like this:
«Arguments are passed by *value*, **unless** their value is an object.  Otherwise they're passed by *reference*».

**Comment by suyashgulati** [comment]
I like the 2nd statement more informative!

**Comment by Herbertusz** [comment]
The mistake in the first sentence is that it is not true. There is no "pass by reference" in javascript. You can modify the inside of the argument if it is an object, because you can access to this object with reference. But this reference passed by value to the function.
If it were truly passed by reference you could modify the original object with assign other value to the argument, but you cannot.
