### ISSUE TITLE
Improve 11 question explanation

### ISSUE THREAD

**Issue by ArtyomBobrovnik** [lydiahallie/javascript-questions#355]
In answer mentioned:

> If you want to add a feature to all objects at once, you have to use the prototype instead.

And it looks good, but

> You can't add properties to a constructor like you can with regular objects

To my mind it's not correct because function is an object and you can use this approach to create a static method.
For example
`new Date()` // Date here is a constructor function
`Date.now()` // static method on this constructor function

**Comment by rosschapman** [comment]
👍  for what @ArtyomBobrovnik says above, though I think it's just a phrasing issue. Instead something like this might be more precise? 
```
You can add properties or methods to a constructor function, but they won't be available on instances of objects returned by calling that constructor function with the `new` operator.
```

Similarly, I was thinking this line -- `If you want to add a feature to all objects at once...` -- could be reworked to read something like: 

```
If you'd like to make a property or method available to all instances created by a constructor function...
```

Lastly, I'm wondering if the issue about wasted memory is the most relevant way to explore the tradeoff between a static and instance methods in this example because the example doesn't address the scoping issue of the `this` and that calling `Person.getFullName()` would never be correct anyway. Perhaps it's not a huge deal but an example like the following that introduces adding the method to the constructor function and instance  might keep the problem free from the `this` binding issue?

```
function Person(firstName, lastName) {
  this.firstName = firstName;
  this.lastName = lastName;
}

const member = new Person('Lydia', 'Hallie');
member.fullName = (member) => Person.getFullName(member);
Person.getFullName = function(person) {
  return `${person.firstName} ${person.lastName}`;
};

console.log(member.getFullName());
```
