### ISSUE TITLE
Separate browser specific and pure JS questions

### ISSUE THREAD

**Issue by savelichalex** [lydiahallie/javascript-questions#37]
Hi guys, thanks for questions. 

I just want to mention that there are many ReactNative and node.js devs who not so interested in browser specific questions during interview, it would be great to separate them.

Thanks.

**Comment by lydiahallie** [comment]
Thanks for your input! I try to make most questions not browser specific, but since most JS devs have a (basic) understanding of the DOM, I added them anyway. I feel like separating them would make the questions a bit chaotic - although what I can do is add labels to them to show when a question is browser/node specific.
