### ISSUE TITLE
Discussion: Question 133 incorrect explanation?

### ISSUE THREAD

**Issue by igalM** [lydiahallie/javascript-questions#373]
```javascript
const myPromise = Promise.resolve(Promise.resolve('Promise!'));

function funcOne() {
  myPromise.then(res => res).then(res => console.log(res));
  setTimeout(() => console.log('Timeout!', 0));
  console.log('Last line!');
}

async function funcTwo() {
  const res = await myPromise;
  console.log(await res);
  setTimeout(() => console.log('Timeout!', 0));
  console.log('Last line!');
}

funcOne();
funcTwo();
```

The explanation states:
`Both the promise and the timeout are asynchronous operations, the function keeps on running while it's busy completing the promise and handling the setTimeout callback. This means that Last line! gets logged first, since this is not an asynchonous operation. This is the last line of funcOne, the promise resolved, and Promise! gets logged. However, since we're invoking funcTwo(), the call stack isn't empty, and the callback of the setTimeout function cannot get added to the callstack yet.`

But I think that the promise in funcOne doesn't reslove and log Promise! until funcTwo starts and then it goes back to funcOne, logs Promise!, and continues to resolve and log the second time.

**Comment by leonlafa** [comment]
Hi, @igalM just to get a little more clarity, what is it that you think is incorrect, the explanation or the answer to the question?

I think that @lydiahallie has correctly explained the solution.

**Comment by effrenus** [comment]
I think answer is partially incorrect.
```js
const myPromise = Promise.resolve(Promise.resolve('Promise!'));
```
Inner promise fulfilled with value `Promise!`, the outer resolve method return inner promise according [25.6.4.6](https://tc39.es/ecma262/#sec-promise.resolve), it doesn't create wrapper.
```js
function funcOne() {
  myPromise.then(res => res).then(res => console.log(res)); // (1)
  setTimeout(() => console.log('Timeout!', 0)); // (2)
  console.log('Last line!'); // (3)
}

funcOne();
```
(1) Because `myPromise` is resolved we add to microtask queue `NewPromiseReactionJob` (with identity function as fulfill reaction) and return new promise with status `pending`. Then we call `then` method on new promise, because it's not settled, callback `res => console.log(res)` added to `PromiseFulfillReactions` list.
(2) According [8.6](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers) we add new timer task to global queue with timer source.
(3) ⚠️ **Print** `Last line!` 
```js
async function funcTwo() {
  const res = await myPromise; // (4)
  console.log(await res); // (5)
  setTimeout(() => console.log('Timeout!', 0)); // (6)
  console.log('Last line!'); // (7)
}
funcTwo();
```
(4) According [6.2.3.1](https://tc39.es/ecma262/#await) we create promise with value `myPromise`, but the value is already promise so doesn't create wrapper, then perform [`PerformPromiseThen`](https://tc39.es/ecma262/#sec-performpromisethen). As promise is fulfilled add to microtask queue [await fulfilled reaction](https://tc39.es/ecma262/#await-fulfilled). Remove async execution context and return to previous (`6.2.3.1-10`).

`async` functions returns `Promise`, so we create _implicit_ promise and return. More details in "[Faster async functions and promises](https://v8.dev/blog/fast-async)"

Call stack is empty so we must execute all tasks in microtask queue if not empty before next event loop.

* Executing callback from (1) `res => res`, resolve promise returned after first `then` with value `res` and for each callback (fulfill reaction) add to microtask queue [`NewPromiseReactionJob`](https://tc39.es/ecma262/#sec-newpromisereactionjob). In our case its `res => console.log(res)`.
* Next take task from (4) in queue, restore async function context and continue execution from previous point (4) with resolved value `Promise!`. Because `res` is primitive value there is no need to do `await res`, anyway again create promise and resolve with `Promise!` after that add to microtask queue `NewPromiseReactionJob`. Suspend execution, remove async execution context from stack.
* Microtask is not emty so get next job, executing `res => console.log(res)` and ⚠️ **print** `Promise!`
* Next job from microtask resume async function, ⚠️ **print** `Promise!`
* (6) According [8.6](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers) we add new timer task to global queue with timer source.
* (7) ⚠️ **Print** `Last line!`
* Microtask queue is empty, run next event loop. Take from timer queue and execute callback from (2), ⚠️ **print** `Timeout!`.
* On next loop repeat previous step: ⚠️ **print** `Timeout!`.
* Finish execution.

Used resources:
* https://tc39.es/ecma262/
* https://html.spec.whatwg.org/
* https://v8.dev/blog/fast-async
* https://www.stefanjudis.com/today-i-learned/promise-resolution-with-objects-including-a-then-property/

//cc @lydiahallie

**Comment by innomerphey** [comment]
@effrenus thank you, great explanation.
