### ISSUE TITLE
bigint

### ISSUE THREAD

**Issue by ThomasR** [lydiahallie/javascript-questions#40]
In the answer to Question 39, the `bigint` type is mentioned. It should be noted that this is not standardized yet.

**Comment by A1rPun** [comment]
@ThomasR In Node & Chrome you can use BigInt already. [BigInt is currently in stage 3 of the ECMAScript specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) and will be the first new primitive type added to JavaScript since Symbol in ES2015.

No need to explicit state it's not standarized IMHO. We are developers, not standstillers.
