### ISSUE TITLE
question 61

### ISSUE THREAD

**Issue by ghh-l-djl** [lydiahallie/javascript-questions#524]
在node环境下和浏览器环境下结果不同。
node下运行结果为：
{ name: 'Lydia' }
[ 'name' ]

**Comment by ghh-l-djl** [comment]
node版本：v14.15.0

**Comment by Alan-Liang** [comment]
[How the implementation prints args is up to the implementation](https://console.spec.whatwg.org/#printer), so probably we shouldn't use `console.log` as an output function for objects since it is not well-defined. Perhaps passing it to `JSON.stringify()` first? It ignores all non-enumerable properties.

Translation of issue description: The results differs in node and the browser. Node prints out:
```js
{ name: 'Lydia' }
[ 'name' ]
```

**Comment by efleurine** [comment]
I also tested this answer and unless we set the property to `enumerable` to begin with it won't show up in `console.log`.
