### ISSUE TITLE
Question 114's answer is incorrect

### ISSUE THREAD

**Issue by yourme9** [lydiahallie/javascript-questions#710]
The answer says setInterval is an arrow function  so thus bound to the config object.the callback function still holds a reference to the config object.
But for my test, ‘this’ points to the global Window object. The config object will be recycled.
This is my test ,use FinalizationRegistry
![image](https://user-images.githubusercontent.com/73214101/213136879-975dc1aa-2195-44d4-8af7-db1b96959e5f.png)

**Comment by adilrana03** [comment]
Hey, from the last 4-5 days, I am reading these questions and find these interesting. 
can you please assign me this issue?

**Comment by alexandercerutti** [comment]
The answer to 114 is actually correct ("C"). Its explanation feels to be quite off-topic! There was another discussion on this: #505 which led to #537. But still, the first part of the explanation feels off-topic to me.

First of all, the garbage collection is not ensured to be executed. It runs according to several heuristics that are different from browser to browser. This translates to `FinalizationRegistry` execution not happening on my system (I ran the same code you proposed).

Second, `setInterval` saves the callback inside the browser internals to be executed on its own and returns the Interval ID. It does not depend on the fact that `config` is still there or not.

So this should be the correct explanation:

~~Normally when we set objects equal to null, those objects get garbage collected as there is no reference anymore to that object. However, since the callback function within setInterval is an arrow function (thus bound to the config object), the callback function still holds a reference to the config object. As long as there is a reference, the object won't get garbage collected.~~ **Since this is an interval, setting config to null or delete-ing config.alert won't garbage-collect the interval, so the interval will still be called. It should be cleared with clearInterval(config.alert) to remove it from memory. Since it was not cleared, the setInterval callback function will still get invoked every 1000ms (1s).**

___

Just a little side note about the collection of `config`. I tried to check the differences with the original code by adding a reference to the `config` variable in different positions.

<details>
<summary>No reference to <code>config</code></summary>

<img width="790" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/58c23081-c965-4e8c-913a-062775d28113">

<img width="762" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/721fc3ec-b40e-4fd4-a596-bb72974cf8d2">
</details>

<details>
<summary>Reference to <code>config</code> in callback</summary>

<img width="835" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/920e7988-c0f3-4b55-95ec-becbf3659739">

<img width="733" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/ad102d0d-6461-48e3-9d5f-4c09fd555ca7">
</details>

<details>
<summary>Reference to <code>config</code> in callback's <code>console.log</code></summary>

<img width="670" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/e52c09f5-7087-4b5e-935e-a42e65cf019b">

<img width="734" alt="immagine" src="https://github.com/lydiahallie/javascript-questions/assets/5442545/728655a4-7228-445a-b775-52c7900eaff2">
</details>

So, as you can see, even if what Chrome and Firefox do under the hood is probably and somehow the same, Firefox shows more information here and we can see that:

- `config` gets sliced off the scope of the callback if there is no reference to it (at all)
- `config` gets included as `null` if there's any reference in the callback

But the fact the variable gets optimized away doesn't mean it will get _garbage-collected_ any time soon.
