### ISSUE TITLE
Question 12 - the explanation could be better.

### ISSUE THREAD

**Issue by wujekbogdan** [lydiahallie/javascript-questions#82]
It would be good to mention that `console.log(sarah);` just calls the `Person` function like it was a regular function (because it is a regular function :)). The function doesn't return anything - that's why the result of its call is `undefined`.

**Comment by A1rPun** [comment]
> because it is a regular function

What defines a **regular** function in your view? Any function can be `new`'ed, intended or not.

**Comment by lydiahallie** [comment]
Fixed 👍

**Comment by rosschapman** [comment]
I'd like to reopen this issue because I think there is still some specificity lost in the current explanation that could benefit others. Just yesterday I was reviewing this question with a colleague and we had a hard time understanding the explanation. I'm largely motivated here by memories of being an early career JS dev and encountering a lot of misdirection around "classes." I'd like to propose the following:

```
To create the value `lydia`, the `Person` function was called with the `new` operator. This is also called _creating an instance of Person_. In_ JavaScript, using `new` transforms a normal function call into a "constructor call" which does four things: 
1.     Creates a blank, plain JavaScript object (in this case inheriting from `Person.prototype`);
2.     Links (sets the constructor of) this object to another object (to `Person.prototype`);
3.     Passes the newly created object from Step 1 as the `this` context;
4.     Returns `this` if the function doesn't return an object.
The browser logs the value returned by step 4 for `lydia`, the `this` that points to the newly created object instance where the properties `firstName` and `lastName` have been set to `Lydia` and `Hallie` respectively.

However, when creating the value for `sarah`, the `Person` function is called normally. JavaScript functions will automatically returned `undefined` if not return statement is present. Additionally, the value of `this` inside of the `Person` function will represent the value of `this` of the outer context. If you execute this code in a browser console, the `window` object will now contain the properties `firstName` and `lastName` assigned to `Sarah` and `Smith` respectively.  
```

I suspect fully explaining the effects step by step the constructor call may be useful in other places constructor calls are used to create class-like objects. By the way, I'm taking that "constructor call" language from Kyle Simpson's chapter on Objects here: https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/this%20%26%20object%20prototypes/ch5.md#constructor-or-call.
